name: Bump version
on:
  push:
    branches:
      - main
    paths-ignore:
      # Don't build a new Docker image if we change only one of the below file paths
      - '.github/**'
      - LICENSE
      - README.md

jobs:
  tag_and_push_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: create_github_tag
      uses: anothrNick/github-tag-action@1.61.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    - name: Log in to Docker Hub
      uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
      with:
        context: .
        push: true
        tags: "jwr0/fargate-dns-updater:${{ steps.create_github_tag.outputs.tag }},jwr0/fargate-dns-updater:latest"
    - name: Create an issue if any step failed
      if: failure()
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "title": "Issue created due to workflow failure: ${{ github.run_id }}",
          "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n due to failure in run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}."
          }'
    - name: Rollback tag if any step failed
      if: failure()
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: false # this project only uses tags, not releases
        tag_name: ${{ steps.create_github_tag.outputs.tag }} # tag name to delete
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
